# Into to Tensor
1D Tensors

Tensor is a generalisation of matrices with N-Dimensions

**Zero Dimensional Tensor** - Scalar

**One Dimensional Tensor** - Vector

**Two Dimensional Tensor** - Matrices

So on..

If torch is not installed
```ipynb
!pip3 install torch
```


In [1]:
import torch
# Building 1D tensor
v = torch.tensor([1,2,3])
print(v)

# To check dtype
print(v.dtype)

# To acess the zeroth index
print(v[0])

tensor([1, 2, 3])
torch.int64
tensor(1)


In [2]:
v = torch.tensor([1,2,3, 4, 5, 6]) # create 1-D tensor output
print(v[1:4])
print(v[1:])

# For float tensor
f = torch.FloatTensor([2,3,4,5,6])

# If you wish to convert v whicn int dtype to float dtype
v_float = v.float()

print("f.dtype = ", f.dtype)
print("f.size()", f.size())

print("v.dtype = ", v.dtype)
print("v.size() = ", v.size())
print(v)
print("v_float.dtype = ", v_float.dtype)
print("v_float.size() = ", v_float.size())
print(v_float)

tensor([2, 3, 4])
tensor([2, 3, 4, 5, 6])
f.dtype =  torch.float32
f.size() torch.Size([5])
v.dtype =  torch.int64
v.size() =  torch.Size([6])
tensor([1, 2, 3, 4, 5, 6])
v_float.dtype =  torch.float32
v_float.size() =  torch.Size([6])
tensor([1., 2., 3., 4., 5., 6.])


### Rearrange this tensor


In [3]:
print("v = ", v)
print("v.view(6,1) = \n", v.view(6,1))

# If size is wrong, it will have Runtime Error for shape.

print("v.view(3,2) = \n", v.view(3,2))

print("v.view(3,-1) = \n", v.view(3,-1))

print("v.view(-1,2) = \n", v.view(-1,2))


v =  tensor([1, 2, 3, 4, 5, 6])
v.view(6,1) = 
 tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
v.view(3,2) = 
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
v.view(3,-1) = 
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
v.view(-1,2) = 
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


### Using Numpy
Convert tensor to numpy

`v.numpy()`

Convert numpy to tensor

`torch.from_numpy(v_np)`

In [4]:
import numpy as np

v_np = np.array([1,2,3,4,5,6])
# or
v_np = v.numpy()
print(v_np.dtype)
print(v_np)

# convert numpy to tensor
tensor_cnv = torch.from_numpy(v_np)
print(tensor_cnv)
print(tensor_cnv.dtype)

int64
[1 2 3 4 5 6]
tensor([1, 2, 3, 4, 5, 6])
torch.int64


# Vector Operations

In [5]:
# 1D tensor
t_one = torch.tensor([1,2,3])
t_two = torch.tensor([1,2,3])

print(t_one + t_two)
print(t_one * t_two)
print(t_one / t_two)
print(t_one * 5)

tensor([2, 4, 6])
tensor([1, 4, 9])
tensor([1., 1., 1.])
tensor([ 5, 10, 15])


In [6]:
dot_product = torch.dot(t_one, t_two)
print(dot_product)

tensor(14)


In [7]:
# torch.linspace(start, end) which prints out 100 equally spaced number between start to end
print(torch.linspace(0, 10))

tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.0808,  8.1818,  8.2828,  8.3838,  8.4848,  8.5859,  8.6869,  8.7879,
         8.8889,  8.9899,  9.0909,  9.1919,  9.2929,  9.3939,  9.4950,  9.5960,
         9.6970,  9.7980,  9.8990, 10.00

/home/eight/anaconda3/envs/torchunity_6_18_2023/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Not providing a value for linspace's steps is deprecated and will throw a runtime error in a future release. This warning will appear only once per process. (Triggered internally at  /tmp/pip-req-build-i4pra_71/aten/src/ATen/native/RangeFactories.cpp:23.)
  
