# 1

In [10]:
# Creating a one dimensitional tensor using torch
import torch

v = torch.tensor([1,2,3, 4, 5, 6]) # create 1-D tensor output
print(v)
print(v.dtype)

print(v[0])
print(v[1])

print(v[1:4])

print(v[1:])

# For float tensor
f = torch.FloatTensor([2,3,4,5,6])

print(f.dtype)
print(f.size())

tensor([1, 2, 3, 4, 5, 6])
torch.int64
tensor(1)
tensor(2)
tensor([2, 3, 4])
tensor([2, 3, 4, 5, 6])
torch.float32
torch.Size([5])
